# Generated by Django 4.2.7 on 2023-12-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0003_remove_appect_user_users_appect_user_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="appect_user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
